using UnityEngine;

namespace TMS.Common.Modularity.Regions
{
	/// <summary>
	/// Interface for ViewMapping
	/// </summary>
	public interface IViewMapping
	{
        /// <summary>
        /// Gets or sets the data context.
        /// </summary>
        /// <value>
        /// The data context.
        /// </value>
        /// <autogeneratedoc />        
        object DataContext { get; set; }

		/// <summary>
		/// Called when [view mapped].
		/// </summary>
		/// <param name="regionHost">The region host.</param>
		/// <param name="view">The view.</param>
		void OnViewMapped(RegionMapping regionHost, GameObject view);

		/// <summary>
		/// Called when [view unmapped].
		/// </summary>
		/// <param name="regionHost">The region host.</param>
		/// <param name="view">The view.</param>
		void OnViewUnmapped(RegionMapping regionHost, GameObject view);
	}
}